### PR TITLE
add gopls.tidy, gopls.run_tests, gopls.list_known_packages lsp command

### PR DESCRIPTION
**Pull request by jackieli-tes**
There are new LSP commands added to gopls. 

This one is particularly helpful: https://github.com/golang/tools/blob/master/gopls/doc/commands.md#run-go-mod-tidy

Usually when I add a new import to the file, gopls will report that the workspace is broken, e.g.:

```
[go list] [E] err: exit status 1: stderr: go: mypackage: package google.golang.org/protobuf/proto imported from implicitly required module; to add missing requirements, run:
      go get google.golang.org/protobuf/proto@v1.26.0
: packages.Load error
```

Usually at this point I run the `go get` outside of vim and run `:CocRestart`

this `gopls.tidy` solves the problem. `gopls` automatically refresh the workspace

Also added `gopls.run_tests`, `gopls.list_known_packages`

### CODE REVIEW

**Comment by luisdavim** [comment]
@josa42 can we get this merged, it solves a major pain point.

**Comment by josa42** [comment]
I am sorry, but I am not going to merge this, I don't want to add more custom commands to the extension. I would merge a PR just adding gopls.tidy though.

**Comment by luisdavim** [comment]
@jackieli-tes would you mind opening a PR with just the `gopls.tidy` part? I think that would greatly improve the UX for this extension.

Thanks

**Comment by luisdavim** [comment]
@josa42 any chances of reconsidering this PR? Having the tidy functionality would make life so much better... And I don't really see how the extra command could cause any trouble...

Thanks.

**Comment by jackieli-tes** [comment]
> @jackieli-tes would you mind opening a PR with just the `gopls.tidy` part? I think that would greatly improve the UX for this extension.
> 
> Thanks

Done in #171. Hope @josa42 is happy with it.

**Pull request closed without merging**
