### PR TITLE
feat: use the module path as the default value of the goimports -local flag

### PR DESCRIPTION
**Pull request by damnever**

### CODE REVIEW

**Comment by damnever** [comment]
@josa42 please take a look.

**Comment by josa42** [comment]
@damnever Can you explain a little why this is needed and why it should be the default behavior?

**Comment by damnever** [comment]
@josa42  so that goimports can group imports like this:
```go
import (
  // stdlib

  // third-party

  // current project
)
```

Maybe we can make an option for the default behavior.

**Comment by damnever** [comment]
Any comments?

**Pull request closed without merging**
